# general parameters
trial_path:             logs
trial_name:             ppo_cartpole
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               1
num_gpus:               0
num_samples:  1
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:   CartPole-v1

# algorithm parameters
agent:               PPO_quantum
total_timesteps:    200000
num_envs:           5
seed:               42
num_steps:          128
anneal_lr:          True
gamma:              0.99
gae_lambda:         0.95
num_minibatches:    4
update_epochs:      4
norm_adv:           True
clip_coef:          0.2
clip_vloss:         True
ent_coef:           0.01
vf_coef:            0.5
max_grad_norm:      0.5
target_kl:          None

lr_input_scaling:   0.01
lr_weights:         0.01
lr_output_scaling:  0.1
num_qubits:         4
num_layers:         5
device:             lightning.qubit
diff_method:        adjoint


cuda: False

