# general parameters
trial_path:             logs
trial_name:             reinforce_cartpole
wandb:                  False

# environment parameters
env_id:   CartPole-v1

# algorithm parameters
env_wrapper:        arctan
agent:              REINFORCE_quantum
total_timesteps:    500000
lr_input_scaling:   0.025  
lr_weights:         0.025    
lr_output_scaling:   0.1    
num_envs:           5
seed:               None
gamma:              0.99
num_qubits:         4
num_layers:         5
ansatz:             hea
init_method:        uniform
observables:        global
device:             lightning.qubit
diff_method:        adjoint
cuda: False
save_model: True
